"""
Django settings for prep_su project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+1@yp!tc46&%5cceem(fh%0hi-t&cp%y+5vx551qa*h(o0woxg'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

#DEBUG = False
if DEBUG is True:
    ALLOWED_HOSTS = []

SITE_ID = 1
# Application definition

INSTALLED_APPS = [
    #'django.contrib.admin',
    'material',
    'material.admin',
    'content.apps.ContentConfig',
    'qs.apps.QsConfig',
    'shop.apps.ShopConfig',
    'actions.apps.ActionsConfig',
    'haystack',
    'django.contrib.auth',
    #'mozilla_django_oidc',
    
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'adminsortable2',
    'compressor',
    'rangefilter',
    'snowpenguin.django.recaptcha3',
    'taggit',
    'django.contrib.sites',
    'django.contrib.sitemaps',    
    'django_summernote', 
    'sorl.thumbnail',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    #'mozilla_django_oidc.middleware.SessionRefresh',
]

ROOT_URLCONF = 'cm28.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        #'APP_DIRS': True,
        'OPTIONS': {
            #'debug': True,
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'shop.context_processors.cart',
                'common.context_processors.main_menu',
                #'common.context_processors.menu_product',
                'django.template.context_processors.static',
            ],
            'loaders': [
                        'django.template.loaders.filesystem.Loader',
                        'django.template.loaders.app_directories.Loader',
                        #'admin_tools.template_loaders.Loader',
                        ],                
        },
    },
]

WSGI_APPLICATION = 'cm28.wsgi.application'

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'
# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
           'ENGINE': 'django.db.backends.mysql',
           'NAME': 'cm28',
           'USER': 'root',
           'PASSWORD': '1111111',
           'HOST': '127.0.0.1',
           'PORT': '3306',
       }  
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

#AUTHENTICATION_BACKENDS = (
    ##'mozilla_django_oidc.auth.OIDCAuthenticationBackend',
    #'django.contrib.auth.backends.ModelBackend',
    ##'account.authentication.EmailAuthBackend',

#)

#OIDC_RP_CLIENT_ID = '34145e80-7a7b-0139-4341-0a20ff17eca7187966'
#OIDC_RP_CLIENT_SECRET = '783253fbeab24aa7cfecf1ca38bad864829f78a8bc0bdfc6a556dfa36f25c430'


##OIDC_RP_CLIENT_ID = '8f7cbef0-7b3b-0139-e2ec-06b3749c7fb3187966'
##OIDC_RP_CLIENT_SECRET = '1b66c863939833519a61afc57bf8cae705d7a2009a01b7138219a9f25649b3c9'

#OIDC_OP_AUTHORIZATION_ENDPOINT = "https://prep-su-dev.onelogin.com/oidc/2/auth"
#OIDC_OP_TOKEN_ENDPOINT = "https://prep-su-dev.onelogin.com/oidc/2/token"
#OIDC_OP_USER_ENDPOINT = "https://prep-su-dev.onelogin.com/oidc/2/me"

#OIDC_RP_SIGN_ALGO = "RS256"
#OIDC_OP_JWKS_ENDPOINT = "https://contentlab-dev.onelogin.com/oidc/2/certs"

##OIDC_CREATE_USER=True
#OIDC_CREATE_USER = True
##OIDC_STORE_ACCESS_TOKEN=True
##OIDC_TOKEN_USE_BASIC_AUTH=True

#LOGIN_REDIRECT_URL = 'http://localhost:8000'
#LOGIN_URL = 'account:login'
#LOGOUT_URL = 'account:logout'
##LOGIN_REDIRECT_URL = "http://localhost:8000/login/"
#LOGOUT_REDIRECT_URL = "http://localhost:8000/novital.html"
# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_L10N = True

USE_TZ = True

CART_SESSION_ID = 'cart'

HAYSTACK_CONNECTIONS = {
    'default': {
        'ENGINE': 'haystack.backends.whoosh_backend.WhooshEngine',
        #'PATH': os.path.join(os.path.dirname(__file__), 'whoosh_index'),
        'PATH': os.path.join(BASE_DIR, 'search_index'),
          
    },
}

HAYSTACK_SEARCH_RESULTS_PER_PAGE = 10
#  automatic index generation 
HAYSTACK_SIGNAL_PROCESSOR = 'haystack.signals.RealtimeSignalProcessor'
# Static files (CSS, JavaScript, Images)
RECAPTCHA_PRIVATE_KEY = '6Lc8-s0UAAAAAD_2gpOqEyotcBBW2hvioGRbFnJ9'
RECAPTCHA_PUBLIC_KEY = '6Lc8-s0UAAAAAA1Ikoxpet2juxh6tPdqOvLI7V45'
RECAPTCHA_DEFAULT_ACTION = 'generic'
RECAPTCHA_SCORE_THRESHOLD = 0.5
RECAPTCHA_LANGUAGE = 'en'
#STATICFILES_STORAGE = 'static_compress.CompressedStaticFilesStorage'
#STATIC_COMPRESS_FILE_EXTS = ['js', 'css', 'svg','jpg','png']
#STATIC_COMPRESS_METHODS = ['gz', 'br']
#STATIC_COMPRESS_KEEP_ORIGINAL = True
#STATIC_COMPRESS_MIN_SIZE_KB = 30
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')
STATICFILES_FINDERS  =  ( 
    'django.contrib.staticfiles.finders.FileSystemFinder' , 
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'compressor.finders.CompressorFinder'

)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

THUMBNAIL_PRESERVE_FORMAT = True
THUMBNAIL_FORCE_OVERWRITE = True

X_FRAME_OPTIONS = 'SAMEORIGIN'
SUMMERNOTE_THEME = 'bs4'
SUMMERNOTE_CONFIG = {
    # Using SummernoteWidget - iframe mode, default
    'iframe': True,
    #'iframe': False,
    # Or, you can set it as False to use SummernoteInplaceWidget by default - no iframe mode
    # In this case, you have to load Bootstrap/jQuery stuff by manually.
    # Use this when you're already using Bootstraip/jQuery based themes.
    #'iframe': False,

    # You can put custom Summernote settings
    'summernote': {
        # As an example, using Summernote Air-mode
        'airMode': False,

        # Change editor size
        'width': '100%',
        'height': '300',
        'toolbar': [
            ['style', ['style']],
            ['font', ['bold', 'underline', 'clear','subscrip','strikethrough']],
            ['color', ['color']],
            ['para', ['ul', 'ol', 'paragraph']],
            ['insert', ['link', 'picture']],
            ['view', ['fullscreen', 'codeview', 'help']],
        ],
        # Use proper language setting automatically (default)
        'lang': 'ru-ru',

        # Or, set editor language/locale forcely
        'lang': 'ru-RU',
        

        # You can also add custom settings for external plugins
        'print': {
            'stylesheetUrl': '/some_static_folder/printable.css',
           },
        'codemirror': {
            'mode': 'htmlmixed',
            'lineNumbers': 'true',
            # You have to include theme file in 'css' or 'css_for_inplace' before using it.
            #'theme': 'default',
            'theme': 'monokai',
        },        
    },

    # Need authentication while uploading attachments.
    'attachment_require_authentication': True,

    # Set `upload_to` function for attachments.
    #'attachment_upload_to': my_custom_upload_to_func(),

    # Set custom storage class for attachments.
    #'attachment_storage_class': 'my.custom.storage.class.name',

    # Set custom model for attachments (default: 'django_summernote.Attachment')
    #'attachment_model': 'my.custom.attachment.model', # must inherit 'django_summernote.AbstractAttachment'

    # You can disable attachment feature.
    'disable_attachment': False,

    ## You can add custom css/js for SummernoteWidget.
    #'css': (
    #),
    #'js': (
    #),

    ### You can also add custom css/js for SummernoteInplaceWidget.
    ### !!! Be sure to put {{ form.media }} in template before initiate summernote.
    'css_for_inplace': (
       
        '//cdnjs.cloudflare.com/ajax/libs/codemirror/5.29.0/theme/abcdef.min.css', 
        '//cdnjs.cloudflare.com/ajax/libs/codemirror/5.29.0/theme/monokai.min.css',  
        #'summernote/monokai.min.css',
    ),
    'js_for_inplace': (
            'summernote/codemirror.js',
           '//cdnjs.cloudflare.com/ajax/libs/codemirror/3.20.0/mode/xml/xml.js',
           '//cdnjs.cloudflare.com/ajax/libs/codemirror/2.36.0/formatting.js', 
           'summernote/htmlmixed-lint.js'
           #'summernote/jquery.ui.widget.js',
           #'/static/summernote/ResizeSensor.js',
           #'summernote/summernote-bs4.min.js',
           #'summernote/summernote-lite.min.js',
           #'//somewhere_in_internet/summernote-plugin-name.js',           
    ),

    ### Codemirror as codeview
    ### If any codemirror settings are defined, it will include codemirror files automatically.
    'css': (
            #'//cdnjs.cloudflare.com/ajax/libs/codemirror/5.29.0/theme/monokai.min.css ' ,
            ##'summernote/monokai.min.css',
            #'//cdnjs.cloudflare.com/ajax/libs/codemirror/5.29.0/theme/abcdef.min.css',  
            #'//cdnjs.cloudflare.com/ajax/libs/codemirror/5.29.0/theme/cobalt.min.css',  
            #'//cdnjs.cloudflare.com/ajax/libs/codemirror/5.29.0/theme/idea.min.css',  
            #'//cdnjs.cloudflare.com/ajax/libs/codemirror/5.29.0/theme/seti.min.css',  
            #'//cdnjs.cloudflare.com/ajax/libs/codemirror/5.29.0/theme/neo.min.css',  
            #'//cdnjs.cloudflare.com/ajax/libs/codemirror/5.29.0/theme/default.min.css', 
            '//cdnjs.cloudflare.com/ajax/libs/codemirror/5.29.0/theme/monokai.min.css',  
            #'summernote/monokai.min.css',
            #'summernote/summernote-lite.css',
            #'summernote/summernote-bs4.css',
            ),
    'codemirror': {
        'mode': 'htmlmixed',
        'lineNumbers': 'true',
        'lineWrapping': 'true',
        'fixedGutter': 'true',
        'gutter': 'true',
        # You have to include theme file in 'css' or 'css_for_inplace' before using it.
        #'theme': 'abcdef',
        'theme': 'monokai',
       
    },

    ## Lazy initialize
    ## If you want to initialize summernote at the bottom of page, set this as True
    ## and call `initSummernote()` on your page.
    'lazy': True,

    ## To use external plugins,
    ## Include them within `css` and `js`.
    #'js': {
        ##'/staic/summernote/summernote-bs4.min.js',
        #'/staic/summernote/jquery.ui.widget.js',
        #'/staic/summernote/ResizeSensor.js',
        ###'//somewhere_in_internet/summernote-plugin-name.js',
    #},
}


MATERIAL_ADMIN_SITE = {
    'HEADER': 'Административная часть 28cm',  # Admin site header
    'TITLE':'Административная часть 28cm',  # Admin site title
    'FAVICON':'images/logo/logo32_black.svg',  # Admin site favicon (path to static should be specified)
    'MAIN_BG_COLOR':  '#04537c;',  # Admin site main color, css color should be specified
    #'MAIN_HOVER_COLOR':  'color',  # Admin site main hover color, css color should be specified
    #'PROFILE_PICTURE':  '/images/l_a1.png',  # Admin site profile picture (path to static should be specified)
    #'PROFILE_BG':  '/images/bg_admin.jpg',  # Admin site profile background (path to static should be specified)
    #'LOGIN_LOGO':  '/images/logo1_w.png',  # Admin site logo on login page (path to static should be specified)
    #'LOGOUT_BG':  '/images/bga.jpg',  # Admin site background on login/logout pages (path to static should be specified)
    #'SHOW_THEMES':  False,  #  Show default admin themes button
    'SHOW_THEMES':  True,  #  Show default admin themes button
    'TRAY_REVERSE': True,  # Hide object-tools and additional-submit-line by default
    'NAVBAR_REVERSE': True,  # Hide side navbar by default  
    'SHOW_COUNTS': True, # Show instances counts for each model
    'APP_ICONS': {  # Set icons for applications(lowercase), including 3rd party apps, {'application_name': 'material_icon_name', ...}
        'sites': 'send',
    },
    'MODEL_ICONS': {  # Set icons for models(lowercase), including 3rd party models, {'model_name': 'material_icon_name', ...}
        'site': 'contact_mail',
    }
}

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.PyMemcacheCache',
        'LOCATION': '127.0.0.1:11211',
    }
}