# Generated by Django 3.2 on 2021-04-25 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Пользователь')),
                ('verb', models.CharField(max_length=255, verbose_name='Действие')),
                ('verbico', models.CharField(max_length=150, verbose_name='Иконка')),
                ('target_id', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Название')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата')),
                ('target_ct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_obj', to='contenttypes.contenttype', verbose_name='Название')),
            ],
            options={
                'verbose_name_plural': 'Активность',
                'ordering': ('-created',),
            },
        ),
    ]
