# Generated by Django 3.2 on 2021-04-25 10:01

import common.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название')),
                ('title', models.CharField(max_length=250, verbose_name='Титл категории')),
                ('meta_description', models.CharField(max_length=250, verbose_name='Мета категории')),
                ('meta_keywords', models.CharField(blank=True, max_length=250, verbose_name='КейВорд категории')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('sort', common.fields.OrderField(blank=True, help_text='Порядок сортировки', verbose_name='Порядок сортировки')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Слаг')),
                ('active', models.BooleanField(default=True, verbose_name='Статус')),
                ('stattext', models.TextField(help_text='Статистика текста', max_length=40000, verbose_name='Статистика текста')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'Категории',
                'ordering': ('-sort',),
            },
        ),
        migrations.CreateModel(
            name='MedRazdel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название раздела', max_length=200, verbose_name='Название раздела')),
                ('namefile', models.SlugField(blank=True, help_text='Путь к категории', max_length=100, null=True, verbose_name='Путь к категории')),
                ('image', models.ImageField(blank=True, upload_to='medrazdel/%Y/%m', verbose_name='Изображение')),
                ('about', models.TextField(help_text='О разделе', max_length=40000, verbose_name='')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата ')),
                ('sort', common.fields.OrderField(blank=True, help_text='Порядок сортировки', verbose_name='<>')),
                ('active', models.BooleanField(default=True, verbose_name='Статус')),
            ],
            options={
                'verbose_name_plural': 'Раздел',
                'ordering': ['-sort'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('last_name', models.CharField(max_length=50, verbose_name='Имя, Отчество')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Индекс')),
                ('address', models.CharField(max_length=250, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('payment', models.CharField(choices=[('1', 'Оплата наличными'), ('2', 'Наложенный платеж'), ('3', 'Через Сбербанк')], help_text='Метод оплаты', max_length=2, verbose_name='Метод оплаты')),
                ('summa', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма заказа')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновление')),
                ('paid', models.BooleanField(default=False, verbose_name='Оплачен')),
            ],
            options={
                'verbose_name_plural': 'Заказы',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название')),
                ('title', models.CharField(help_text='Титл препарата', max_length=250, verbose_name='Титл страницы')),
                ('meta_description', models.CharField(max_length=250, verbose_name='Мета препарата')),
                ('meta_keywords', models.CharField(blank=True, max_length=250, verbose_name='КейВорд препарата')),
                ('slug', models.SlugField(max_length=200, verbose_name='Слаг')),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d', verbose_name='Изображение')),
                ('about', models.TextField(blank=True, help_text='Краткое пояснение', verbose_name='Краткое пояснение')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('priem', models.TextField(blank=True, help_text='Как принимать', max_length=1000, verbose_name='Как принимать')),
                ('sostav', models.TextField(blank=True, help_text='Состав', verbose_name='Состав')),
                ('kurs', models.CharField(blank=True, help_text='Курс приема', max_length=550, verbose_name='Курс приема')),
                ('izgotovitel', models.CharField(blank=True, help_text='Производитель', max_length=550, verbose_name='Производитель')),
                ('sertifikat', models.CharField(blank=True, help_text='Сертификат', max_length=250, verbose_name='Сертификат')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стоимость')),
                ('available', models.BooleanField(default=True, verbose_name='В наличии')),
                ('sort', common.fields.OrderField(blank=True, help_text='Порядок сортировки', verbose_name='Порядок сортировки')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Когда создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновление')),
                ('best', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Лучший товар')),
                ('sale', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Скидка')),
                ('orderlink', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Где купить')),
                ('stattext', models.TextField(help_text='Статистика текста', max_length=40000, verbose_name='Статистика текста')),
                ('total_raiting', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Оценка')),
                ('active', models.BooleanField(default=True, verbose_name='Статус')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name_plural': 'Товары',
                'ordering': ('-sort',),
                'index_together': {('id', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Имя')),
                ('email', models.EmailField(max_length=150, verbose_name='E-mail')),
                ('body', models.TextField(verbose_name='Отзыв')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создание')),
                ('modified', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Обновление')),
                ('active', models.BooleanField(default=True, help_text='Вкл / Выкл', verbose_name='Статус')),
                ('rating', models.CharField(blank=True, choices=[('0', 'Плохо'), ('1', 'Не очень'), ('2', 'Средне'), ('3', 'Нормально'), ('4', 'Хорошо'), ('5', 'Отлично')], default='0', help_text='Оценка', max_length=1, verbose_name='Оценка')),
                ('product', models.ForeignKey(limit_choices_to={'active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shop.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name_plural': 'Отзывы',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='shop.product', verbose_name='Продукт')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='var',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medrazdel', to='shop.medrazdel', verbose_name='Раздел'),
        ),
    ]
