# Generated by Django 3.2 on 2021-04-25 10:01

import common.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название страницы', max_length=250, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, help_text='Имя файла', max_length=100, verbose_name='Имя файла')),
                ('title', models.CharField(help_text='Титл страницы', max_length=250, verbose_name='Титл страницы')),
                ('meta_description', models.CharField(max_length=250, verbose_name='Мета страницы')),
                ('meta_keywords', models.CharField(max_length=250, verbose_name='КейВорд страницы')),
                ('image', models.ImageField(blank=True, null=True, upload_to='block/%Y/', verbose_name='Первое')),
                ('main', models.TextField(max_length=40000, verbose_name='Содержание')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, help_text='Дата Создания', verbose_name='Создание')),
                ('enddate', models.DateTimeField(default=django.utils.timezone.now, help_text='Дата окончания', verbose_name='Окончание')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('sort', common.fields.OrderField(blank=True, help_text='Порядок сортировки', verbose_name='<>')),
                ('active', models.BooleanField(default=True, verbose_name='Статус')),
            ],
            options={
                'verbose_name_plural': 'Блоки',
                'ordering': ['-sort'],
            },
        ),
        migrations.CreateModel(
            name='Chast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Подраздел', max_length=200, verbose_name='Часть раздела')),
                ('sort', common.fields.OrderField(blank=True, help_text='Порядок сортировки', verbose_name='<>')),
                ('active', models.BooleanField(default=True, verbose_name='Статус')),
            ],
            options={
                'verbose_name_plural': 'Часть',
                'ordering': ['-sort'],
            },
        ),
        migrations.CreateModel(
            name='Razdel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название раздела', max_length=200, verbose_name='Название раздела')),
                ('namefile', models.SlugField(blank=True, help_text='Путь к категории', max_length=100, null=True, verbose_name='Путь к категории')),
                ('title', models.CharField(help_text='Титл раздела', max_length=250, verbose_name='Титл страницы')),
                ('meta_description', models.CharField(max_length=250, verbose_name='Мета раздела')),
                ('meta_keywords', models.CharField(max_length=250, verbose_name='КейВорд раздела')),
                ('image', models.ImageField(blank=True, null=True, upload_to='razdel/%Y/%m/%d/', verbose_name='Первое')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='razdel/%Y/%m/%d/', verbose_name='Второе изображение')),
                ('about', models.TextField(help_text='О разделе', max_length=40000, verbose_name='')),
                ('main', models.TextField(max_length=40000, verbose_name='')),
                ('stattext', models.TextField(help_text='Статистика текста', max_length=40000, verbose_name='Статистика текста')),
                ('sort', common.fields.OrderField(blank=True, help_text='Порядок сортировки', verbose_name='<>')),
                ('block', models.TextField(blank=True, help_text='Баннер', max_length=40000, null=True, verbose_name='Баннер')),
                ('block_active', models.BooleanField(default=True, verbose_name='Баннер')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Дата ')),
                ('active', models.BooleanField(default=True, verbose_name='Статус')),
            ],
            options={
                'verbose_name_plural': 'Раздел',
                'ordering': ['-sort'],
            },
        ),
        migrations.CreateModel(
            name='RuTag',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('taggit.tag',),
        ),
        migrations.CreateModel(
            name='RuTaggedItem',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('taggit.taggeditem',),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название страницы', max_length=250, verbose_name='Название')),
                ('namefile', models.SlugField(blank=True, help_text='Имя файла', max_length=100, verbose_name='Имя файла')),
                ('title', models.CharField(help_text='Титл страницы', max_length=250, verbose_name='Титл страницы')),
                ('meta_description', models.CharField(max_length=250, verbose_name='Мета страницы')),
                ('meta_keywords', models.CharField(max_length=250, verbose_name='КейВорд страницы')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pub/%Y/%m/%d/', verbose_name='Изображение')),
                ('main', models.TextField(max_length=60000, verbose_name='Содержание')),
                ('stattext', models.TextField(help_text='Статистика текста', max_length=40000, verbose_name='Статистика текста')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, help_text='Дата Создания', verbose_name='Создание')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('sort', common.fields.OrderField(blank=True, help_text='Порядок сортировки', verbose_name='<>')),
                ('active', models.BooleanField(default=True, verbose_name='Статус')),
                ('ch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chrazdel', to='content.chast', verbose_name='Подраздел')),
                ('productlink', models.ForeignKey(blank=True, help_text='Продукт', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pageproduct', to='shop.product', verbose_name='Продукт')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='content.RuTaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name_plural': 'Страницы',
                'ordering': ['-sort'],
            },
        ),
        migrations.AddField(
            model_name='chast',
            name='var',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chastrazdel', to='content.razdel', verbose_name='Раздел'),
        ),
    ]
