# Generated by Django 3.2 on 2021-04-25 10:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='pages',
            field=models.ManyToManyField(to='content.Section', verbose_name='list of sites'),
        ),
        migrations.AddField(
            model_name='section',
            name='sloganheader',
            field=models.CharField(default=1, max_length=250, verbose_name='Слоган страницы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='top_page',
            field=models.TextField(default=django.utils.timezone.now, max_length=60000, verbose_name='Вверх страницы'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='section',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pub/%Y/%m/', verbose_name='Изображение'),
        ),
    ]
