# Generated by Django 3.2 on 2021-04-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_section_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='pages',
            field=models.ManyToManyField(blank=True, null=True, to='content.Section', verbose_name='Ещё страницы'),
        ),
        migrations.AlterField(
            model_name='section',
            name='sloganheader',
            field=models.TextField(max_length=1000, verbose_name='Слоган страницы'),
        ),
        migrations.AlterField(
            model_name='section',
            name='top_page',
            field=models.TextField(max_length=500, verbose_name='Вверх страницы'),
        ),
    ]
